curl https://archives.bulbagarden.net/media/upload/thumb/1/17/Body01.png/64px-Body01.png --output 01.png
curl https://archives.bulbagarden.net/media/upload/thumb/b/bc/Body07.png/64px-Body07.png --output 07.png
curl https://archives.bulbagarden.net/media/upload/thumb/d/d3/Body03.png/64px-Body03.png --output 03.png 
curl https://archives.bulbagarden.net/media/upload/thumb/4/4b/Body14.png/64px-Body14.png --output 14.png
curl https://archives.bulbagarden.net/media/upload/thumb/c/cc/Body08.png/64px-Body08.png --output 08.png 
curl https://archives.bulbagarden.net/media/upload/thumb/0/09/Body13.png/64px-Body13.png --output 13.png 
curl https://archives.bulbagarden.net/media/upload/thumb/3/36/Body11.png/64px-Body11.png --output 11.png
curl https://archives.bulbagarden.net/media/upload/thumb/9/97/Body10.png/64px-Body10.png --output 10.png 
curl https://archives.bulbagarden.net/media/upload/thumb/d/da/Body05.png/64px-Body05.png --output 05.png 
curl https://archives.bulbagarden.net/media/upload/thumb/8/88/Body06.png/64px-Body06.png --output 06.png 
curl https://archives.bulbagarden.net/media/upload/thumb/4/45/Body12.png/64px-Body12.png --output 12.png 
curl https://archives.bulbagarden.net/media/upload/thumb/9/98/Body09.png/64px-Body09.png --output 09.png
curl https://archives.bulbagarden.net/media/upload/thumb/2/2c/Body04.png/64px-Body04.png --output 04.png
curl https://archives.bulbagarden.net/media/upload/thumb/7/7a/Body02.png/64px-Body02.png --output 02.png