curl https://archives.bulbagarden.net/media/upload/9/95/Normal_icon_SwSh.png --output normal.png
curl https://archives.bulbagarden.net/media/upload/3/3b/Fighting_icon_SwSh.png --output fighting.png
curl https://archives.bulbagarden.net/media/upload/b/b5/Flying_icon_SwSh.png --output flying.png
curl https://archives.bulbagarden.net/media/upload/8/8d/Poison_icon_SwSh.png --output poison.png
curl https://archives.bulbagarden.net/media/upload/2/27/Ground_icon_SwSh.png --output ground.png
curl https://archives.bulbagarden.net/media/upload/1/11/Rock_icon_SwSh.png --output rock.png
curl https://archives.bulbagarden.net/media/upload/9/9c/Bug_icon_SwSh.png --output bug.png
curl https://archives.bulbagarden.net/media/upload/0/01/Ghost_icon_SwSh.png --output ghost.png
curl https://archives.bulbagarden.net/media/upload/0/09/Steel_icon_SwSh.png --output steel.png
curl https://archives.bulbagarden.net/media/upload/a/ab/Fire_icon_SwSh.png --output fire.png
curl https://archives.bulbagarden.net/media/upload/8/80/Water_icon_SwSh.png --output water.png
curl https://archives.bulbagarden.net/media/upload/a/a8/Grass_icon_SwSh.png --output grass.png
curl https://archives.bulbagarden.net/media/upload/7/7b/Electric_icon_SwSh.png --output electric.png
curl https://archives.bulbagarden.net/media/upload/7/73/Psychic_icon_SwSh.png --output psychic.png
curl https://archives.bulbagarden.net/media/upload/1/15/Ice_icon_SwSh.png --output ice.png
curl https://archives.bulbagarden.net/media/upload/7/70/Dragon_icon_SwSh.png --output dragon.png
curl https://archives.bulbagarden.net/media/upload/d/d5/Dark_icon_SwSh.png --output dark.png
curl https://archives.bulbagarden.net/media/upload/c/c6/Fairy_icon_SwSh.png --output fairy.png